ROOT = ../..

SOURCES = \
	GradDescent.cpp \
	MomentumGradDescent.cpp \
	NeuralNet.cpp \
	NeuralNetAlg.cpp \
	NeuralNetReader.cpp \
	NeuralNetWriter.cpp \
	NNetDataStream.cpp \
	Statistics.cpp \

TEST_SOURCES = \
	TestNeuralNetAlg.cpp \
	TestNNetDataset.cpp \
	TestNNetDataStream.cpp \
	TestStatistics.cpp \

include $(ROOT)/mk/buildlib.mk

LIBS += -lautil
