ROOT = ../..

SOURCES = \
	BenchmarkPerformance.cpp \
	Returns.cpp \
	Momentum.cpp \
	MovingAverage.cpp \
	LogNormal3.cpp \
	Normal.cpp \
	DownsideRisk.cpp \
	Risk.cpp \
	PortfolioAlg.cpp \
	PortfolioEval.cpp \
	PortfolioEvolve.cpp \
	PortfolioPermute.cpp \

TEST_SOURCES = \
	TestReturns.cpp \
	TestMomentum.cpp \
	TestMovingAverage.cpp \
	TestIntegrate.cpp \
	TestDownsideRisk.cpp \
	TestLogNormal3.cpp \
	TestPortfolioAlg.cpp \
	TestPortfolioPermute.cpp \

include $(ROOT)/mk/buildlib.mk

LIBS += -lnnet -lstockdata
