######################################################################
# Automatically generated by qmake (1.07a) Sat May 15 13:25:33 2004
######################################################################

TEMPLATE = app
INCLUDEPATH += .

# Input
HEADERS += canvas.h
SOURCES += canvas.cpp main.cpp
